### ISSUE TITLE
Streaming program doesn't stop properly

### ISSUE THREAD

**Issue by lurch** [raspitv/RasPiCamcorder#1]
When running picamstreamer.py, a "medium length" button push is supposed to cause the program to quit. Sometimes it works correctly, but quite often it prints "Closing program" and then carries on printing "streaming status = 0" over and over.

I did a bit of debugging and this is because the finally block of picamstream-sudo.py is still being run, which sets the streaming status back to 0. If you change line 124 to instead write a streaming status of 2 then the 'parent' picamstreamer.py process always shuts down properly.

**Comment by raspitv** [comment]
Dealt with. Thanks Andrew :+1:
