### ISSUE TITLE
picamstreamer leaves multiple VLC processes running in the background

### ISSUE THREAD

**Issue by lurch** [raspitv/RasPiCamcorder#2]
Just been doing some more testing, and discovered that every time you use picamstreamer.py to start and stop streaming, it leaves an extra copy of vlc running in the background! (which over time will eat up more and more memory)

Dug into it, and found that this is because cvlc is merely a shell-script wrapper around vlc, and so whenever you run anything using cvlc, it _actually_ shows up in the process list as vlc (check for yourself by running `ps aux|grep vlc|grep -v grep` in a secondary SSH session), and so therefore the "pkill cvlc" isn't actually doing anything.

If you change line 33 of picamstreamer.py to instead "pkill vlc" it fixes this problem.
And I guess as well as fixing picamstreamer.py in github, it would be nice if you could fix everywhere on http://raspi.tv that you've done this as well.

**Comment by raspitv** [comment]
Good catch. Thanks Andrew. Will deal with that immediately.

**Comment by raspitv** [comment]
This has been corrected (but I haven't yet tested it, although Andrew has).
